import { purple, neutral, yellow, red, green, blond, hotPink } from "./colors";
import { primaryFont, displayFont } from "./typography";

export const defaultTheme = {
    primaryColor: purple[200],
    primaryColorDarker: purple[400],
    primaryColorHover: purple[450],
    primaryColorActive: purple[200],
    navText: purple[400],
    invertedButtonText: blond[500],
    disabled: purple[100],
    textColorOnPrimary: neutral[600],
    textColorOnDark: blond[200],
    blondBackground: blond[500],
    blond: blond[500],
    gray: neutral[400],
    navColor: neutral[100],
    dropdownColor: '#E7E7E7',
    hyperlinkColor: purple[200],
    invertedNavColor: purple[400],
    textColor: neutral[600],
    textColorInverted: neutral[100],
    textDark: neutral[600],
    darkToBlond: neutral[600],
    textOnDisabled: neutral[300],
    formElementBackground: neutral[100],
    textOnFormElementBackground: neutral[600],
    primaryFont,
    displayFont,
    status: {
        warningColor: yellow[100],
        warningColorHover: yellow[200],
        warningColorActive: yellow[300],
        errorColor: red[100],
        errorColorHover: red[200],
        errorColorActive: red[300],
        successColor: green[100],
        successColorHover: green[200],
        successColorActive: green[300]
      }
}

export const darkTheme = {
    primaryColor: neutral[100],
    primaryColorDarker: purple[400],
    primaryColorHover: purple[450],
    primaryColorActive: neutral[100],
    navText: blond[500],
    invertedButtonText: purple[400],
    disabled: purple[100],
    textColorOnPrimary:  blond[200],
    blondBackground: purple[400],
    blond: blond[500],
    gray: neutral[500],
    navColor: purple[400],
    dropdownColor: purple[400],
    hyperlinkColor: hotPink[200],
    invertedNavColor: blond[500],
    textColorOnDark: purple[400],
    textColor: purple[300],
    textColorInverted: neutral[100],
    textOnDisabled: neutral[300],
    textDark: neutral[600],
    darkToBlond: blond[500],
    formElementBackground: purple[400],
    textOnFormElementBackground: neutral[100],
    primaryFont,
    displayFont,
    status: {
        warningColor: yellow[100],
        warningColorHover: yellow[200],
        warningColorActive: yellow[300],
        errorColor: red[100],
        errorColorHover: red[200],
        errorColorActive: red[300],
        successColor: green[100],
        successColorHover: green[200],
        successColorActive: green[300]
      }
}